import { FC, Fragment, ReactNode } from "react";
import { AbsoluteFill, interpolate, spring, useCurrentFrame } from "remotion";

type Item = { label?: string; value?: string; detail?: string };
type Visual = { kicker?: string; headline?: string; subheadline?: string; metric?: string; unit?: string; body?: string; items?: Item[]; steps?: string[]; nodes?: Item[]; timeline?: Item[]; code_lines?: string[]; device?: string };
export type DirectorSceneData = { visual_type: string; purpose?: string; priority?: string; layout?: string; animation?: string; transition?: string; background?: string; accent?: string; fact_check_required?: boolean; visual?: Visual };

const FONT = "Arial, Helvetica, sans-serif";
const C = { white:"#F7F7F4", muted:"rgba(255,255,255,.56)", line:"rgba(255,255,255,.18)", faint:"rgba(255,255,255,.07)" };
const ACCENT: Record<string,string> = { cyan:"#8FE8FF", blue:"#9CB8FF", amber:"#FFD38B", violet:"#C5A6FF", red:"#FF9A94" };
const ac = (x?:string) => ACCENT[x || ""] || "#FFFFFF";

const Frame: FC<{children:ReactNode}> = ({children}) => <AbsoluteFill style={{justifyContent:"center",alignItems:"center",padding:110,fontFamily:FONT}}>{children}</AbsoluteFill>;
const Header: FC<{v:Visual;a:string}> = ({v,a}) => <div style={{marginBottom:34}}>{v.kicker && <div style={{fontSize:18,letterSpacing:4,fontWeight:700,color:a,marginBottom:14}}>{v.kicker.toUpperCase()}</div>}{v.headline && <div style={{fontSize:62,lineHeight:.98,fontWeight:800,letterSpacing:-2}}>{v.headline}</div>}{v.subheadline && <div style={{marginTop:16,fontSize:23,color:C.muted,maxWidth:950}}>{v.subheadline}</div>}</div>;

function Typography({v,a}:{v:Visual;a:string}){const f=useCurrentFrame();const y=interpolate(f,[0,18],[34,0],{extrapolateLeft:"clamp",extrapolateRight:"clamp"});return <Frame><div style={{width:"86%",transform:"translateY("+y+"px)"}}><Header v={v} a={a}/><div style={{fontSize:106,lineHeight:.92,fontWeight:800,maxWidth:1500}}>{v.body||v.headline}</div></div></Frame>}
function NumberCard({v,a}:{v:Visual;a:string}){const f=useCurrentFrame();const p=spring({frame:f-3,fps:30,config:{damping:18,stiffness:110}});return <Frame><div style={{textAlign:"center"}}><Header v={v} a={a}/><div style={{display:"flex",alignItems:"baseline",justifyContent:"center",gap:18,transform:"scale("+Math.max(0,p)+")"}}><div style={{fontSize:190,lineHeight:.9,fontWeight:800,letterSpacing:-8}}>{v.metric}</div>{v.unit&&<div style={{fontSize:48,color:a,fontWeight:700}}>{v.unit}</div>}</div></div></Frame>}
function Bars({v,a}:{v:Visual;a:string}){const f=useCurrentFrame();const items=(v.items||[]).slice(0,5);const nums=items.map(x=>parseFloat(String(x.value||"").replace(",",".").replace(/[^0-9.-]/g,""))).filter(Number.isFinite);const max=Math.max.apply(null,nums.length?nums:[1]);return <Frame><div style={{width:1450}}><Header v={v} a={a}/>{items.map((x,i)=>{const n=parseFloat(String(x.value||"").replace(",",".").replace(/[^0-9.-]/g,""));const r=Number.isFinite(n)?n/max:.35;const w=interpolate(f,[i*5,i*5+22],[0,Math.max(8,r*100)],{extrapolateLeft:"clamp",extrapolateRight:"clamp"});return <div key={i} style={{marginTop:22}}><div style={{display:"flex",justifyContent:"space-between",fontSize:23,marginBottom:8}}><span>{x.label}</span><b style={{color:a}}>{x.value}</b></div><div style={{height:13,background:C.faint}}><div style={{width:w+"%",height:"100%",background:"linear-gradient(90deg,"+a+",rgba(255,255,255,.9))"}}/></div></div>})}</div></Frame>}
function Compare({v,a}:{v:Visual;a:string}){const f=useCurrentFrame();const items=(v.items||[]).slice(0,3);return <Frame><div style={{width:1450}}><Header v={v} a={a}/><div style={{display:"grid",gridTemplateColumns:"repeat("+Math.max(1,items.length)+",1fr)",gap:20}}>{items.map((x,i)=>{const p=interpolate(f,[i*7,i*7+18],[0,1],{extrapolateLeft:"clamp",extrapolateRight:"clamp"});return <div key={i} style={{minHeight:260,padding:34,border:"1px solid "+C.line,background:"rgba(255,255,255,.025)",opacity:p,transform:"translateY("+((1-p)*18)+"px)"}}><div style={{color:a,fontSize:17,letterSpacing:2}}>{x.label}</div><div style={{fontSize:64,fontWeight:800,marginTop:20}}>{x.value}</div>{x.detail&&<div style={{marginTop:14,color:C.muted,fontSize:20}}>{x.detail}</div>}</div>})}</div></div></Frame>}
function Donut({v,a}:{v:Visual;a:string}){const f=useCurrentFrame();const raw=parseFloat(String(v.metric||"").replace(",",".").replace(/[^0-9.-]/g,""));const pct=Number.isFinite(raw)?Math.max(0,Math.min(100,raw)):0;const deg=interpolate(f,[0,28],[0,pct*3.6],{extrapolateLeft:"clamp",extrapolateRight:"clamp"});return <Frame><div style={{display:"flex",alignItems:"center",gap:90}}><div style={{width:360,height:360,borderRadius:"50%",background:"conic-gradient("+a+" 0deg "+deg+"deg,rgba(255,255,255,.1) "+deg+"deg 360deg)",display:"grid",placeItems:"center"}}><div style={{width:270,height:270,borderRadius:"50%",background:"#050505",display:"grid",placeItems:"center",textAlign:"center"}}><div style={{fontSize:78,fontWeight:800}}>{v.metric}</div>{v.unit&&<div style={{fontSize:20,color:a}}>{v.unit}</div>}</div></div><div style={{width:560}}><Header v={v} a={a}/>{v.body&&<div style={{fontSize:23,color:C.muted}}>{v.body}</div>}</div></div></Frame>}
function Timeline({v,a}:{v:Visual;a:string}){const f=useCurrentFrame();const pts=(v.timeline||[]).slice(0,6);const line=interpolate(f,[0,25],[0,1],{extrapolateLeft:"clamp",extrapolateRight:"clamp"});return <Frame><div style={{width:1500}}><Header v={v} a={a}/><div style={{position:"relative",height:300}}><div style={{position:"absolute",left:20,right:20,top:80,height:2,background:C.line}}/><div style={{position:"absolute",left:20,top:79,height:4,width:(line*100)+"%",background:a}}/>{pts.map((x,i)=>{const p=interpolate(f,[i*5+8,i*5+20],[0,1],{extrapolateLeft:"clamp",extrapolateRight:"clamp"});const left=pts.length<2?50:i/(pts.length-1)*100;return <div key={i} style={{position:"absolute",left:left+"%",top:68,transform:"translateX(-50%) scale("+(.5+p*.5)+")",opacity:p}}><div style={{width:24,height:24,borderRadius:"50%",background:a,boxShadow:"0 0 25px "+a+"55"}}/><div style={{position:"absolute",top:48,left:"50%",transform:"translateX(-50%)",width:210,textAlign:"center"}}><div style={{color:a,fontWeight:700}}>{x.value}</div><div style={{fontSize:22,fontWeight:700,marginTop:6}}>{x.label}</div>{x.detail&&<div style={{fontSize:16,color:C.muted,marginTop:4}}>{x.detail}</div>}</div></div>})}</div></div></Frame>}
function Flow({v,a}:{v:Visual;a:string}){const f=useCurrentFrame();const s=(v.steps||[]).slice(0,5);return <Frame><div style={{width:1450}}><Header v={v} a={a}/><div style={{display:"flex",alignItems:"stretch",gap:14}}>{s.map((text,i)=><Fragment key={i}><div style={{flex:1,minHeight:180,padding:28,border:"1px solid "+C.line,opacity:interpolate(f,[i*5,i*5+14],[0,1],{extrapolateLeft:"clamp",extrapolateRight:"clamp"})}}><div style={{color:a,letterSpacing:2}}>0{i+1}</div><div style={{fontSize:25,fontWeight:700,marginTop:24}}>{text}</div></div>{i<s.length-1&&<div style={{alignSelf:"center",color:a,fontSize:30}}>→</div>}</Fragment>)}</div></div></Frame>}
function Diagram({v,a}:{v:Visual;a:string}){const f=useCurrentFrame();const nodes=(v.nodes||v.items||[]).slice(0,5);return <Frame><div style={{width:1500}}><Header v={v} a={a}/><div style={{position:"relative",height:430}}><div style={{position:"absolute",left:"50%",top:40,transform:"translateX(-50%)",width:270,height:100,border:"2px solid "+a,display:"grid",placeItems:"center",fontSize:24,fontWeight:700}}>{v.metric||"SISTEMA"}</div>{nodes.map((x,i)=>{const p=interpolate(f,[i*5,i*5+18],[0,1],{extrapolateLeft:"clamp",extrapolateRight:"clamp"});const left=15+i*(70/Math.max(1,nodes.length-1));const top=255+(i%2)*95;return <div key={i}><div style={{position:"absolute",left:"50%",top:90,width:Math.max(40,Math.abs(left-50)*25),height:2,background:a,transform:"scaleX("+p+")",transformOrigin:"left",opacity:.5}}/><div style={{position:"absolute",left:left+"%",top,transform:"translate(-50%,-50%)",width:250,padding:20,border:"1px solid "+C.line,background:"rgba(255,255,255,.025)",opacity:p}}><b style={{color:a}}>{x.label}</b>{x.detail&&<div style={{marginTop:7,color:C.muted,fontSize:16}}>{x.detail}</div>}</div></div>})}</div></div></Frame>}
function Device({v,a}:{v:Visual;a:string}){const f=useCurrentFrame();const p=spring({frame:f,fps:30,config:{damping:20,stiffness:90}});const laptop=/laptop|notebook|computer/i.test(v.device||"");return <Frame><div style={{width:1450,display:"flex",justifyContent:"space-between",alignItems:"center"}}><div style={{width:620}}><Header v={v} a={a}/>{(v.items||[]).slice(0,4).map((x,i)=><div key={i} style={{padding:"15px 0",borderTop:"1px solid "+C.faint}}><span style={{color:a}}>{x.label}</span>{x.detail&&<span style={{color:C.muted}}> — {x.detail}</span>}</div>)}</div><div style={{transform:"scale("+(.9+.1*Math.max(0,p))+")",opacity:p}}>{laptop?<div style={{width:620,height:330,border:"3px solid "+a,borderRadius:20,padding:18}}><div style={{height:"100%",border:"1px solid "+C.line}}/></div>:<div style={{width:250,height:520,border:"3px solid "+a,borderRadius:34,padding:15}}><div style={{height:"100%",border:"1px solid "+C.line,borderRadius:24,background:"linear-gradient(150deg,rgba(255,255,255,.07),rgba(255,255,255,.01))"}}/></div>}</div></div></Frame>}
function Code({v,a}:{v:Visual;a:string}){const f=useCurrentFrame();return <Frame><div style={{width:1450}}><Header v={v} a={a}/><div style={{padding:32,border:"1px solid "+C.line,background:"#090909",fontFamily:"monospace",fontSize:21}}>{(v.code_lines||[]).slice(0,10).map((l,i)=><div key={i} style={{opacity:interpolate(f,[i*3,i*3+8],[0,1],{extrapolateLeft:"clamp",extrapolateRight:"clamp"}),lineHeight:1.55}}><span style={{display:"inline-block",width:55,color:"rgba(255,255,255,.22)",textAlign:"right",marginRight:18}}>{i+1}</span><span style={{color:i%3===0?a:C.white}}>{l}</span></div>)}</div></div></Frame>}
function Concept({v,a}:{v:Visual;a:string}){const f=useCurrentFrame();return <Frame><div style={{width:1450,display:"flex",alignItems:"center",justifyContent:"space-between"}}><div style={{width:600}}><Header v={v} a={a}/></div><div style={{width:520,height:520,position:"relative",transform:"rotate("+f*.5+"deg)"}}>{[170,260,350].map((s,i)=><div key={s} style={{position:"absolute",left:"calc(50% - "+s/2+"px)",top:"calc(50% - "+s/2+"px)",width:s,height:s,border:"1px solid "+(i===2?a:C.line),borderRadius:"50%"}}/>)}<div style={{position:"absolute",left:"calc(50% - 40px)",top:"calc(50% - 40px)",width:80,height:80,borderRadius:"50%",background:a,boxShadow:"0 0 40px "+a+"66"}}/></div></div></Frame>}
function Editorial({v,a}:{v:Visual;a:string}){return <AbsoluteFill style={{justifyContent:"flex-end",padding:110,fontFamily:FONT}}><div style={{maxWidth:1250}}><Header v={v} a={a}/>{v.body&&<div style={{fontSize:26,color:C.muted,maxWidth:1000}}>{v.body}</div>}</div></AbsoluteFill>}

export const DirectorScene: FC<{scene:DirectorSceneData;durationInFrames:number}> = ({scene,durationInFrames}) => {
  const f=useCurrentFrame(); const a=ac(scene.accent); const v=scene.visual||{};
  const inF=Math.min(18,Math.max(1,durationInFrames));
  const opacity=Math.min(interpolate(f,[0,inF],[0,1],{extrapolateLeft:"clamp",extrapolateRight:"clamp"}),interpolate(f,[Math.max(0,durationInFrames-12),durationInFrames],[1,0],{extrapolateLeft:"clamp",extrapolateRight:"clamp"}));
  let content:ReactNode;
  switch(scene.visual_type){
    case "kinetic_typography": case "quote_card": content=<Typography v={v} a={a}/>; break;
    case "number_callout": case "data_callout": content=<NumberCard v={v} a={a}/>; break;
    case "bar_chart": content=<Bars v={v} a={a}/>; break;
    case "donut_chart": content=<Donut v={v} a={a}/>; break;
    case "comparison": content=<Compare v={v} a={a}/>; break;
    case "timeline": content=<Timeline v={v} a={a}/>; break;
    case "process_flow": content=<Flow v={v} a={a}/>; break;
    case "system_diagram": case "network": content=<Diagram v={v} a={a}/>; break;
    case "device_blueprint": content=<Device v={v} a={a}/>; break;
    case "code_window": content=<Code v={v} a={a}/>; break;
    case "concept_visual": case "ambient": content=<Concept v={v} a={a}/>; break;
    default: content=<Editorial v={v} a={a}/>;
  }
  const bg=scene.background==="offwhite"?"#F3F2EE":"#050505";
  const color=scene.background==="offwhite"?"#090909":C.white;
  const backdrop=scene.background==="grid" ? {backgroundImage:"linear-gradient("+C.line+" 1px,transparent 1px),linear-gradient(90deg,"+C.line+" 1px,transparent 1px)",backgroundSize:"72px 72px"} : {background:"radial-gradient(circle at 75% 25%,"+a+"22,transparent 35%)"};
  return <AbsoluteFill style={{background:bg,color,opacity,overflow:"hidden"}}>{(scene.background==="grid"||scene.background==="gradient")&&<AbsoluteFill style={{opacity:.28,...backdrop}}/>}{content}{scene.fact_check_required&&<div style={{position:"absolute",right:32,top:26,fontSize:11,letterSpacing:2,color:"rgba(255,255,255,.25)"}}>FACT-CHECK</div>}</AbsoluteFill>;
};
